npm test src/tests/01
npm test src/tests/02
npm test src/tests/03
npm test src/tests/04
npm test src/tests/05
npm test src/tests/06
npm test src/tests/07
npm test src/tests/08
npm test src/tests/09
npm test src/tests/10
npm test src/tests/11
npm test src/tests/12
npm test src/tests/13
npm test src/tests/14